add maxlenght and remove errors
faisalakb/Portfolio-website1 pull request #4
Opened 2023-02-28 13:13 UTC by faisalakb

Please check the PR. 
This project has the following features.  
- Updated form section in Mobile Portfolio version. 👍 
- Added footer sections. 👍  
- In forms, use [Formspree](https://formspree.io/forms) for form submission. 👍 
- Apply validation on forms. 👍

2023-02-28 13:50 UTC, faisalakb commented
Updated the required changes as you mentioned above under PR.

2023-02-28 14:21 UTC, roshan-bajgain requested changes
Hi @faisalakb, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good design ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 14:21 UTC, roshan-bajgain commented on index.html
> +          <li><textarea class="inp3" name="micro_text" placeholder="Enter text here" maxlength="500" rows="5" cols="42"></textarea></li>
- [ ] I would suggest you please use the required attribute on textarea to activate the validation on submit.

2023-02-28 14:21 UTC, roshan-bajgain commented on index.html
>            </ul>
- [ ] According to the project requirement you should stick to the design as much as possible. I would suggest you please provide padding to the placeholder and also please make your button stick to the Figma design
- [ ] Also provide the same color for the placeholder in textarea and small line is missing there please implement it also see Figma image below for reference.
### Your design
![his](https://user-images.githubusercontent.com/81727988/221879160-c82aa28f-dfe3-4ad2-acb4-a3a52a0afa14.png)

### Figma design

![fimga](https://user-images.githubusercontent.com/81727988/221880807-58bcefa4-aae6-498e-b1fe-e5437ac9625d.png)

2023-02-28 16:17 UTC, faisalakb commented
Please check my PR. I updated all the above comments/

2023-02-28 17:09 UTC, adel-gu requested changes
# Status: Required Changes ♻️ 
**Hi @faisalakb 👋🏼** 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes 💪🏼💪🏼💪🏼, but there are still some which aren't been addressed yet.  🚀🚀🚀

![](https://media3.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif?cid=ecf05e47cureydsgd56hjmktg6zdo3hydxgqs7x8zuep7t5o&rid=giphy.gif&ct=g)

 ## Highlights
- Good commit history ✔️ 
- Well presented PR ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 17:09 UTC, adel-gu commented on index.html
>            </form>
- [ ] Sorry this wasn't mentioned by the previous reviewer, In the form element I can see that the background image is been added as an `img` so it will be counted as content from the screen reader and it looks more like a decorative rather than content, for that reason I highly suggest setting this image as a background-image using CSS instead.

- And kindly fix its position so it will look like the Figma design as much as possible, and it always sticks to the right side of the screen.
- The image is at line: 
![image](https://user-images.githubusercontent.com/68030297/221924733-96b03c38-427a-4923-92d4-11eec08f028b.png)


### Your Design
![image](https://user-images.githubusercontent.com/68030297/221924245-16658f58-d4f9-4146-b28b-e8a16fe9beba.png)

### Figma Design
![image](https://user-images.githubusercontent.com/68030297/221924340-e043a29d-d850-4585-92fb-7cd60d828478.png)

2023-02-28 17:09 UTC, adel-gu commented on style.css
>    .getIn:hover {
- [ ] Please consider sticking to the Figma Design as much as possible and kindly follow the button interaction as shown in the Figma design.

### Your Design
![image](https://user-images.githubusercontent.com/68030297/221925386-1bed828f-ee51-4265-90a6-f800086b6d71.png)

### Figma Design
![image](https://user-images.githubusercontent.com/68030297/221925496-e12218a2-6e65-4836-b01c-47e831fc5f1e.png)

2023-03-01 09:14 UTC, faisalakb commented
Please check my PR, I updated all the above points. Please note for `textarea` resize icon is clearly shown at the bottom right on the full screen. However, when you put it into mobile format icon is still there, but the size shrinks.

2023-03-01 10:18 UTC, souad988 requested changes
Hi @faisalakb , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![212385281-4797c58a-d358-423a-aa7c-832c22203865](https://user-images.githubusercontent.com/59707859/222110590-f56939e8-6db7-4f48-877b-b2b6d3f45680.gif)


## Highlights
✔No linter issues
✔Good efforts 
✔Good use of github workflow
✔Good PR title

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
Hi <STUDENT_MENTION>, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 10:18 UTC, souad988 commented on style.css
> +    background: #36b37f;
@faisalakb  Good job on making some of the requested changes by the previous reviewer , but please make sure to add a box-shadow on hover as in the figma desing and also your button doesn't change color on press event

2023-03-01 10:31 UTC, faisalakb commented on style.css
> +    background: #36b37f;
@souad988 Could you please elaborate on your question? Because I didn't get it, and also there are no above instructions given by the previous reviewer. 
![image](https://user-images.githubusercontent.com/70527740/222113535-99a91446-b994-4faf-87f5-c6fba1a6a591.png)
In the project its for the hovering effect not clicking the button.

2023-03-01 15:37 UTC, osamaashraf6 approved these changes
Hi @faisalakb 😊, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![Congratulations!GIF](https://user-images.githubusercontent.com/83360636/222187338-43328489-42c4-4d20-a594-1f4c57181ca9.gif)


## Highlights👏💯👌🎉

- [x] Good using the formspree✔️
- [x] Good putting the validation for the form✔️
- [x] No linter errors. ✔️
- [x] Good usage in correcting GitHub flow.✔️
- [x] Nice design.✔️

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-01 15:47 UTC, faisalakb commented
Thanks to all the reviewers for your time and comments.

2023-03-01 15:47 UTC, merged